# src/generator/response.py
from langchain.chains import LLMChain
# from langchain.chains.combine_documents import StuffDocumentsChain
from langchain.chains.retrieval_qa.base import RetrievalQA
from langchain.prompts import PromptTemplate




def generate_answer(query, retriever, llm):
    """
    Retrieve context from vector store and generate a response using the LLM.
    """
    # Create RAG chain
    rag_chain = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever,
        chain_type="stuff",  # combine all docs into one prompt
        return_source_documents=True
    )

    result = rag_chain({"query": query})
    answer = result["result"]
    sources = [doc.metadata.get("source") for doc in result["source_documents"]]
    
    return {"answer": answer, "sources": sources}


def construct_prompt(query_text: str, retrieved_chunks, chat_history):
    pass


# The response_builder.py file would be responsible for taking the raw output from the RAG chain (which is typically just the LLM's generated text) and transforming it into a more structured, user-friendly, or application-specific response. This could involve:

# Extracting specific information: If the LLM generates a long answer, you might want to pull out just the core answer, or specific entities.

# Adding metadata: Appending the sources (titles, URLs) of the retrieved documents to the answer.

# Formatting for display: Converting plain text into markdown, HTML, or a specific JSON format for an API.

# Post-processing: Running sentiment analysis, keyword extraction, or other NLP tasks on the LLM's raw output.

# Error handling/fallbacks: Providing a standardized "I don't know" message if the LLM couldn't find an answer.

# response_builder.py Content
# code
# Python
# download
# content_copy
# expand_less
# # response_builder.py

# from typing import List, Dict, Any, Optional

# class ResponseBuilder:
#     """
#     Handles post-processing and formatting of the RAG chain's output.
#     """
#     def __init__(self, include_sources: bool = True):
#         """
#         Initializes the ResponseBuilder.

#         Args:
#             include_sources: Whether to attempt to include source documents in the final response.
#         """
#         self.include_sources = include_sources

#     def build_response(self,
#                        llm_raw_output: str,
#                        retrieved_documents: Optional[List[Dict]] = None,
#                        user_query: Optional[str] = None) -> Dict:
#         """
#         Constructs a structured response from the LLM's raw output and retrieved documents.

#         Args:
#             llm_raw_output: The raw text generated by the LLM.
#             retrieved_documents: An optional list of dictionaries representing the retrieved documents.
#                                  Each dict is expected to have 'text' and 'metadata'.
#             user_query: The original user query.

#         Returns:
#             A dictionary containing the structured response (e.g., {'answer': ..., 'sources': ..., 'query': ...}).
#         """
#         final_answer = self._format_llm_output(llm_raw_output)
#         sources_info = self._extract_sources_info(retrieved_documents) if self.include_sources else []

#         response = {
#             "answer": final_answer,
#             "sources": sources_info,
#             "query": user_query,
#             "raw_llm_output": llm_raw_output # Keep raw output for debugging/transparency
#         }

#         return response

#     def _format_llm_output(self, llm_output: str) -> str:
#         """
#         Applies any specific formatting or post-processing to the LLM's text.
#         e.g., trim whitespace, handle specific "I don't know" phrases.
#         """
#         formatted_output = llm_output.strip()

#         # Example: if your LLM is prone to starting with "Answer: " you could remove it
#         if formatted_output.lower().startswith("answer:"):
#             formatted_output = formatted_output[len("answer:"):].strip()

#         # Example: Standardize "I don't know" messages
#         if any(phrase in formatted_output.lower() for phrase in ["i don't know", "not in the provided context"]):
#             formatted_output = "I couldn't find a definitive answer in the provided documents."

#         return formatted_output

#     def _extract_sources_info(self, retrieved_documents: Optional[List[Dict]]) -> List[Dict]:
#         """
#         Extracts relevant information from retrieved documents to present as sources.
#         """
#         if not retrieved_documents:
#             return []

#         sources = []
#         unique_sources = set() # To avoid listing the same source multiple times

#         for doc in retrieved_documents:
#             metadata = doc.get('metadata', {})
#             source_id = metadata.get('original_source_id') or metadata.get('source_id')
#             source_title = metadata.get('title') or f"Document {source_id}"
#             source_url = metadata.get('url')

#             if source_id and source_id not in unique_sources:
#                 source_entry = {"id": source_id, "title": source_title}
#                 if source_url:
#                     source_entry["url"] = source_url
#                 # You might also include a snippet of the text from the document
#                 source_entry["snippet"] = doc.get("text", "")[:200] + "..." if len(doc.get("text", "")) > 200 else doc.get("text", "")

#                 sources.append(source_entry)
#                 unique_sources.add(source_id)
#             elif not source_id:
#                 # Handle cases where source_id might be missing
#                 sources.append({"id": f"unknown_source_{len(sources)}", "snippet": doc.get("text", "")[:200] + "..."})

#         return sources
# How to Integrate with rag_chain_builder.py and main.py

# To use the ResponseBuilder, you'll need to slightly modify your RAG chain's structure. The rag_chain_builder will need to retain the retrieved_documents so they can be passed to the ResponseBuilder.

# 1. Modified rag_chain_builder.py:

# We'll adjust the chain to keep both the llm_output and retrieved_documents.

# code
# Python
# download
# content_copy
# expand_less
# # rag_chain_builder.py (Modified)

# from typing import List, Dict, Any
# from langchain_core.runnables import RunnablePassthrough, RunnableLambda, RunnableParallel
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_core.output_parsers import StrOutputParser
# from langchain_core.language_models import BaseChatModel, BaseLanguageModel
# # from retriever import Retriever
# # from response_builder import ResponseBuilder # Import your ResponseBuilder


# def format_docs(docs: List[Dict]) -> str:
#     """Formats retrieved documents into a single string for the LLM context."""
#     return "\n\n".join(doc.get("text", "") for doc in docs)


# def create_rag_chain(
#     retriever_instance: Any,
#     llm_client: BaseChatModel | BaseLanguageModel,
#     prompt_template_str: str
# ):
#     """
#     Constructs and returns a LangChain RAG chain that outputs raw LLM answer and retrieved docs.
#     """
#     prompt = ChatPromptTemplate.from_template(prompt_template_str)

#     # Define the core RAG logic that gets the LLM answer
#     rag_answer_chain = (
#         {"context": retriever_instance.retrieve_documents | RunnableLambda(format_docs),
#          "question": RunnablePassthrough()}
#         | prompt
#         | llm_client
#         | StrOutputParser()
#     )

#     # Now, combine the retrieval step with the answer generation step
#     # We want to keep the original retrieved documents for the ResponseBuilder
#     # and also get the final LLM answer.
#     final_rag_chain = RunnableParallel(
#         # The retriever will run on the incoming question and its output (documents) will be saved
#         retrieved_documents=retriever_instance.retrieve_documents,
#         # The LLM answer chain will also run on the incoming question
#         llm_raw_output=rag_answer_chain,
#         # Pass the original question through for the ResponseBuilder
#         original_question=RunnablePassthrough()
#     )

#     return final_rag_chain

# # DEFAULT_RAG_PROMPT_TEMPLATE as before
# DEFAULT_RAG_PROMPT_TEMPLATE = """You are an AI assistant that answers questions based on provided context.
# If the answer is not in the context, clearly state that you don't know.

# Context:
# {context}

# Question: {question}

# Answer:"""

# 2. Modified main.py:

# This file will now use the ResponseBuilder after invoking the chain.

# code
# Python
# download
# content_copy
# expand_less
# # main.py (Modified)

# import os
# import yaml
# from typing import Dict, Any, List
# # ... (all your mock imports from before) ...

# # Import the new ResponseBuilder
# # from response_builder import ResponseBuilder

# # Mock ResponseBuilder for demonstration
# class MockResponseBuilder:
#     def __init__(self, include_sources: bool = True):
#         self.include_sources = include_sources
#         print("MockResponseBuilder initialized.")
#     def build_response(self, llm_raw_output: str, retrieved_documents: Optional[List[Dict]] = None, user_query: Optional[str] = None) -> Dict:
#         print("Mock: Building response...")
#         return {
#             "answer": f"Formatted: {llm_raw_output.strip()}",
#             "sources": [{"id": doc['id'], "snippet": doc['text'][:50]} for doc in retrieved_documents] if self.include_sources and retrieved_documents else [],
#             "query": user_query,
#             "raw_llm_output": llm_raw_output
#         }


# def main():
#     # ... (Initialization of config, VectorStoreManager, EmbeddingModel, LLMService, Retriever) ...

#     # 1. Load Configuration
#     app_config = load_config()
#     print("Configuration loaded.")

#     # 2. Initialize Vector Store Manager
#     vs_config = app_config.get('vector_store', {})
#     vector_store_manager = MockVectorStoreManager()
#     vector_store_manager.initiate(vs_config)
#     print("Vector Store Manager initialized.")

#     # 3. Initialize Embedding Model (and get the LangChain client)
#     embedding_config = app_config.get('embedding', {})
#     embedding_wrapper = MockEmbeddingModel()
#     embedding_client = embedding_wrapper.embedding_client
#     print("Embedding client initialized.")

#     # 4. Initialize LLM Service (and get the LangChain client)
#     llm_config = app_config.get('llm', {})
#     llm_wrapper = MockLLMService(
#         model_name=llm_config.get("model_name"),
#         temperature=llm_config.get("temperature"),
#         max_output_tokens=llm_config.get("max_output_tokens")
#     )
#     llm_client = llm_wrapper.llm_client
#     print("LLM client initialized.")

#     # 5. Instantiate Retriever
#     retriever = MockRetriever(
#         vector_store_manager_instance=vector_store_manager,
#         embedding_client=embedding_client
#     )
#     print("Retriever instantiated.")

#     # Optional: Ingest some initial documents if the store is empty
#     if vector_store_manager.count_documents() == 0:
#         print("\nVector store is empty. Ingesting sample documents...")
#         sample_raw_docs = [
#             {"text": "The capital of France is Paris. It is known for its beautiful architecture.", "metadata": {"source_id": "doc1", "city": "Paris"}},
#             {"text": "Artificial intelligence is a branch of computer science that deals with machines thinking like humans.", "metadata": {"source_id": "doc2", "topic": "AI"}},
#             {"text": "The Louvre Museum is a famous landmark in Paris.", "metadata": {"source_id": "doc3", "city": "Paris"}}
#         ]
#         retriever.ingest_documents(sample_raw_docs)
#         print(f"Total documents after ingestion: {vector_store_manager.count_documents()}")
#     else:
#         print(f"\nVector store already contains {vector_store_manager.count_documents()} documents.")


#     # 6. Create the RAG Chain
#     rag_chain = create_rag_chain(
#         retriever_instance=retriever,
#         llm_client=llm_client,
#         prompt_template_str=DEFAULT_RAG_PROMPT_TEMPLATE
#     )
#     print("\nRAG chain created.")

#     # 7. Initialize Response Builder
#     response_builder = MockResponseBuilder(include_sources=True) # Replace with your actual ResponseBuilder
#     print("Response Builder initialized.")


#     # 8. Invoke the Chain with a question
#     question = "What is AI and what are some famous places in Paris?"
#     print(f"\nInvoking RAG chain with question: '{question}'")

#     # The chain now returns a dictionary:
#     # {'retrieved_documents': [...], 'llm_raw_output': '...', 'original_question': '...'}
#     chain_output = rag_chain.invoke(question)

#     # 9. Build the final structured response using the ResponseBuilder
#     final_response = response_builder.build_response(
#         llm_raw_output=chain_output['llm_raw_output'],
#         retrieved_documents=chain_output['retrieved_documents'],
#         user_query=chain_output['original_question']
#     )

#     print("\n--- Final Structured Response ---")
#     import json
#     print(json.dumps(final_response, indent=2))
#     print("---------------------------------")

# if __name__ == "__main__":
#     main()